### ISSUE TITLE
Can I able to use this model in NodeJs Backend ?

### ISSUE THREAD

**Issue by NaveenSelva-95** [ponahoum/three-usdz-loader#1]
I need to convert usdz file into other formats. can I use this model to load the usdz file in backend?

**Comment by ponahoum** [comment]
@NaveenSelva-95 this package uses the window context and ThreeJS which is only available in a frontend context (Dom API). 
Technically, you could use the javascript WASM bindings in a Node context using the .js file in /External and call it this way, although i haven't tested it:

```
const usdModule = require("emHdBindings.js");
const usdModuleContext = await usdModule();
const testStage = UsdStage.CreateNew('test.usdz');
```

I will close this ticket for now as it's not planned to make a package that works seamlessly with node.
