### ISSUE TITLE
Compilation Problem

### ISSUE THREAD

**Issue by migo-robben** [ponahoum/three-usdz-loader#3]
Hello, I would like to ask, how did you compile the [Autodesk's USD fork] branch of usdjs? Which platform are you using？I have tried both windows and centos 7，but neither can success. Thank you for your reply !

**Comment by ponahoum** [comment]
Hi @migo-robben, as mentionned [here](https://github.com/autodesk-forks/USD/pull/1), compilation has only been tested on Ubuntu. On my side I'm using Docker with an Ubuntu image on Windows, at first I tried compile regular USD (which was a bit complicated i have to say, need to install a few things before), then when i succeeded, I managed to build the WebAssembly version. Hope that helps you ! At some point, I might take a bit of time to make a public Docker image, but I'm pretty busy those days...
