### ISSUE TITLE
SharedArrayBuffer dependency

### ISSUE THREAD

**Issue by ranbuch** [ponahoum/three-usdz-loader#8]
Can we have a way to not be dependent on `SharedArrayBuffer` and just have the `WebAssembly` return an `ArrayBuffer` by value instead?

Allowing `SharedArrayBuffer` is very restrictive.

**Comment by ponahoum** [comment]
@ranbuch I'm afraid that is a requirement of the Autodesk implementation in WebAssembly (https://github.com/autodesk-forks/USD/tree/release). It might be possible to get rid of SharedArrayBuffers, but it's a bit out of scope for this package which is just a wrapper around Autodesk's implementation. Closing for now.
